// import dogImage from '/src/images/dog.jpeg';

//== ***** ***** ***** Exported Object ***** ***** ***** ==//
export const PRODUCTS = [
  {
    id: 1,
    name: 'luis',
    href: '#',
    price: '$0',
    description: 'Colored painting of Luis on canvas using acrylic.',
    type: 'Painting',
    medium: 'Canvas',
    utensil: 'Acrylic',
    imageSrc: 'src/images/luis.png',
    imageAlt: 'Colored painting of Luis on canvas using acrylic.',
    tag: 'People',
    status: 'Completed',
  },
  {
    id: 2,
    name: 'fkj',
    href: '#',
    price: '$0',
    description:
      'Portrait of FKJ. Black and white drawing using pencil on paper.',
    type: 'Drawing',
    medium: 'Paper',
    utensil: 'Pencil',
    imageSrc: 'src/images/fkj.png',
    imageAlt: 'FKJ portrait drawn with pencil on paper.',
    tag: 'People',
    status: 'Completed',
  },
  {
    id: 3,
    name: 'hb',
    href: '#',
    price: '$0',
    description:
      'Black and white painting of Hailey Bieber on canvas using acrylic.',
    type: 'Painting',
    medium: 'Canvas',
    utensil: 'Acrylic',
    imageSrc: 'src/images/hb.png',
    imageAlt:
      'Black and white painting of Hailey Beiber on canvas using acrylic.',
    tag: 'People',
    status: 'Completed',
  },
  {
    id: 4,
    name: 'kids',
    href: '#',
    price: '$0',
    description:
      'Portrait of children. Black and white painting using acrylic on canvas.',
    type: 'Painting',
    medium: 'Canvas',
    utensil: 'Acrylic',
    imageSrc: 'src/images/kids.png',
    imageAlt:
      'Portrait of children. Black and white painting using acrylic on canvas.',
    tag: 'People',
    status: 'Completed',
  },
  {
    id: 5,
    name: 'remi',
    href: '#',
    price: '$0',
    description:
      'Digital painting of our dog, Remi, on the iPad using Procreate.',
    type: 'Digital',
    medium: 'iPad',
    utensil: 'Procreate',
    imageSrc: 'src/images/remi.png',
    imageAlt: 'Digital painting of our dog, Remi, on the iPad using Procreate.',
    tag: 'Animals',
    status: 'Completed',
  },
  {
    id: 6,
    name: 'woman',
    href: '#',
    price: '$0',
    description: 'Digital painting of a woman on the iPad using Procreate.',
    type: 'Digital',
    medium: 'iPad',
    utensil: 'Procreate',
    imageSrc: 'src/images/woman.png',
    imageAlt: 'Digital painting of a woman on the iPad using Procreate.',
    tag: 'People',
    status: 'Completed',
  },
  {
    id: 7,
    name: 'dog',
    href: '#',
    price: '$0',
    description:
      'This was a combination of digital and physical art. I drew this dog on the iPad using Procreate. Then I printed it onyo a canvas and painted over it to make it more textured.',
    type: 'Painting',
    medium: 'Canvas',
    utensil: 'Procreate + Acrylic',
    imageSrc: 'src/images/dog.jpeg',
    imageAlt:
      'Digital painting of a dog, printed on a canvas, and painted over.',
    tag: 'Animals',
    status: 'Completed',
  },
  {
    id: 8,
    name: 'shannon_dog',
    href: '#',
    price: '$0',
    description: 'Painting of the late Mr. Lincoln with a ball.',
    type: 'Painting',
    medium: 'Canvas',
    utensil: 'Acrylic',
    imageSrc: 'src/images/shannon_dog.jpeg',
    imageAlt: 'Painting of the late Mr. Lincoln with a ball.',
    tag: 'Animals',
    status: 'Completed',
  },
  {
    id: 9,
    name: 'girl',
    href: '#',
    price: '$0',
    description: 'Black and white painting of a girl on cardboard.',
    type: 'Painting',
    medium: 'Cardboard',
    utensil: 'Acrylic',
    imageSrc: 'src/images/girl.png',
    imageAlt: 'Black and white painting of a girl on cardboard.',
    tag: 'People',
    status: 'Completed',
  },
  {
    id: 10,
    name: 'jm',
    href: '#',
    price: '$0',
    description:
      'Black and white painting of John Mayer on canvas using acrylic.',
    type: 'Painting',
    medium: 'Canvas',
    utensil: 'Acrylic',
    imageSrc: 'src/images/jm.png',
    imageAlt: 'Black and white painting of John Mayer on canvas using acrylic.',
    tag: 'People',
    status: 'Completed',
  },
  {
    id: 11,
    name: 'leo',
    href: '#',
    price: '$0',
    description: 'Black and white painting of Leonardo DiCaprio',
    type: 'Painting',
    medium: 'Canvas',
    utensil: 'Acrylic',
    imageSrc: 'src/images/leo.png',
    imageAlt: 'Black and white painting of Leonardo DiCaprio.',
    tag: 'People',
    status: 'Completed',
  },
  {
    id: 12,
    name: 'london',
    href: '#',
    price: '$0',
    description: 'Colored painting of London the dog',
    type: 'Painting',
    medium: 'Canvas',
    utensil: 'Watercolor',
    imageSrc: 'src/images/london.png',
    imageAlt: 'Colored painting of London the dog',
    tag: 'Animals',
    status: 'Completed',
  },
  // Practice using a different image import format
  // {
  //   id: 13,
  //   name: 'dog_2',
  //   href: '#',
  //   price: '$0',
  //   description:
  //     'This was a combination of digital and physical art. I drew this dog on the iPad using Procreate. Then I printed it onyo a canvas and painted over it to make it more textured.',
  //   type: 'Painting',
  //   medium: 'Canvas',
  //   utensil: 'Procreate + Acrylic',
  //   imageSrc: dogImage,
  //   imageAlt:
  //     'Digital painting of a dog, printed on a canvas, and painted over.',
  //   tag: 'Animals',
  //   status: 'Completed',
  // },
  // More products...
];
